### ISSUE TITLE
Soundcloud params don't seem to be working

### ISSUE THREAD

**Issue by akoebbe** [Sommerregen/grav-plugin-mediaembed#8]
I've tried setting the following ```params``` settings for Soundcloud, but none of them seem to have any effect...

```yaml
services:
  SoundCloud:
    enabled: true           # Set to false to disable this service completely
    type: "rich"            # Type of the media service

    example: "https://soundcloud.com/semiseria/verruckert-ausschnitt"

    # URL of media service used for embedding
    url: "w.soundcloud.com/player/?url=http://api.soundcloud.com/tracks/{:id}"

    # Canonical URL of media service (used in endpoint calls)
    canonical: "http://soundcloud.com/{:id}"

    # Endpoint to grab media informations
    endpoint: "http://soundcloud.com/oembed?url={:canonical}&format=json"

    # Schemes to grab media id
    schemes:
      - "soundcloud.com/*"
      - "soundcloud.com/*/*"
      - "soundcloud.com/*/sets/*"
      - "soundcloud.com/groups/*"
      - "snd.sc/*"

    params:
      auto_play: true
      buying: true
      download: true
      hide_related: false
      liking: true
      sharing: true
      show_artwork: false
      show_comments: false
      show_playcount: false
      show_user: false
      visual: false
```
